# Default application configuration that all configurations inherit from.
scss_files: "**/*.scss"

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BorderZero:
    enabled: true

  ColorKeyword:
    enabled: true

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: false

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    character: space # or 'tab'
    width: 2

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: false

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: BEM # or 'hyphenated_lowercase', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 3

  PlaceholderInExtend:
    enabled: true

  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    order:
      - box-sizing

      - display

      - flex-direction
      - flex-wrap
      - flex-flow
      - justify-content
      - align-items
      - align-content

      - order
      - flex-grow
      - flex-shrink
      - flex-basis
      - flex
      - align-self

      - visibility
      - overflow

      - position
      - top
      - right
      - bottom
      - left
      - z-index

      - float
      - clear

      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left

      - outline

      - border
      - border-top
      - border-right
      - border-bottom
      - border-left

      - border-width
      - border-top-width
      - border-right-width
      - border-bottom-width
      - border-left-width

      - border-style
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style

      - border-color
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color

      - border-radius

      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left

      - width
      - min-width
      - max-width

      - height
      - min-height
      - max-height

      - transform

      - font
      - font-family
      - font-size
      - font-weight

      - line-height

      - text-align
      - text-indent
      - text-transform
      - text-decoration
      - text-shadow

      - color
      - background
      - background-color
      - background-image
      - background-repeat
      - background-position
      - background-size
      - background-attachment
      - box-shadow

      - transition
      - transition-duration

      - opacity

      - content
      - quotes

  PropertySpelling:
    enabled: true
    extra_properties: []

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM # or BEM, or 'hyphenated_lowercase', or 'snake_case', or 'camel_case', or a regex pattern
    ignored_names:
      - royalSlider
      - rsArrow
      - rsArrowIcn
      - rsArrowLeft
      - rsArrowRight
      - rsBtnCenterer
      - rsCaption
      - rsContent
      - rsGCaption
      - rsHor
      - rsImg
      - rsNav
      - rsNavSelected
      - rsOverflow
      - rsPlayBtn
      - rsPlayBtnIcon
      - rsSlide
      - rsTab
      - rsTabs
      - rsThumb
      - rsThumbs
      - rsThumbsArrow
      - rsThumbsArrowDisabled
      - rsThumbsArrowIcn
      - rsThumbsArrowLeft
      - rsThumbsArrowRight
      - rsThumbsContainer
      - rsThumbsHor
      - rsThumbsVer
      - rsTmb
      - rsVideoContainer
      - rsVideoFrameHolder
      - rsWithThumbsHor
      - rsWithThumbsVer

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: double_quotes # or single_quotes

  TrailingSemicolon:
    enabled: true

  TrailingZero:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VendorPrefixes:
    enabled: true
    identifier_list: base
    include: []
    exclude: []

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
